### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/rathena-script-lang-interpreter#1]
## Bases
- [ ] antlr grammar
- [ ] parser
- [ ] VM architecture

## Features
- [ ] native function calling
- [ ] local variable assignement to constant
- [ ] local variable assignement to expression
- [ ] local variable load
- [ ] function definition
- [ ] function calling
- [ ] instance variable
- [ ] for loop
- [ ] while loop
- [ ] if/else
- [ ] command (menu/warp, etc...) evaluated as native function
- [ ] NPC/Server/Account/char scopes evaluated as syntaxic sugar for native function calling (set/get_(npc,server,account,char)_var
